version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next-pwa
    versions:
    - 5.0.5
    - 5.0.6
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: styled-components
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
  - dependency-name: styled-icons
    versions:
    - 10.27.0
    - 10.28.0
    - 10.29.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
    - 7.12.17
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: strapi-plugin-email
    versions:
    - 3.5.4
  - dependency-name: strapi-admin
    versions:
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi
    versions:
    - 3.5.4
  - dependency-name: strapi-plugin-upload
    versions:
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-plugin-content-type-builder
    versions:
    - 3.5.4
  - dependency-name: strapi-utils
    versions:
    - 3.5.3
    - 3.5.4
  - dependency-name: strapi-plugin-content-manager
    versions:
    - 3.5.4
  - dependency-name: strapi-plugin-graphql
    versions:
    - 3.5.4
  - dependency-name: knex
    versions:
    - 0.95.3
  - dependency-name: strapi-connector-bookshelf
    versions:
    - 3.5.4
  - dependency-name: "@ckeditor/ckeditor5-build-classic"
    versions:
    - 27.0.0
  - dependency-name: strapi-plugin-users-permissions
    versions:
    - 3.5.3
